DROP DATABASE portfolio;

DROP TABLE users;

ALTER TABLE users DROP COLUMN whatever;

TRUNCATE TABLE users;

DELETE FROM users WHERE id=2;

REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'portusr'@'%';

fuser -k 5000/tcp